title: "Music Classification: Beyond Supervised Learning, Towards Real-world Applications"
#logo: images/bd.svg
execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_admonition