title: "Music Classification: Beyond Supervised Learning, Towards Real-world Applications"
author: Minz Won, Janne Spijkervet, Keunwoo Choi
#logo: images/bd.svg
execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_admonition

launch_buttons:
  notebook_interface: "classic"
  colab_url: "https://colab.research.google.com"
  thebe: true
  binderhub_url: "https://mybinder.org"

html:
  favicon: images/favicon_io/favicon.ico
  home_page_in_navbar  : false
  use_repository_button: true
  google_analytics_id: UA-208590538-1

repository:
  url           : "https://github.com/music-classification/tutorial"
  branch        : main
  path_to_book  : book

bibtex_bibfiles:
  - references.bib
